/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: example.proto */

#ifndef PROTOBUF_C_example_2eproto__INCLUDED
#define PROTOBUF_C_example_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _FstMsg FstMsg;


/* --- enums --- */


/* --- messages --- */

struct  _FstMsg
{
  ProtobufCMessage base;
  ProtobufCBinaryData value;
  int32_t data;
};
#define FST_MSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fst_msg__descriptor) \
    , {0,NULL}, 0 }


/* FstMsg methods */
void   fst_msg__init
                     (FstMsg         *message);
size_t fst_msg__get_packed_size
                     (const FstMsg   *message);
size_t fst_msg__pack
                     (const FstMsg   *message,
                      uint8_t             *out);
size_t fst_msg__pack_to_buffer
                     (const FstMsg   *message,
                      ProtobufCBuffer     *buffer);
FstMsg *
       fst_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fst_msg__free_unpacked
                     (FstMsg *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*FstMsg_Closure)
                 (const FstMsg *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor fst_msg__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_example_2eproto__INCLUDED */
